#!/bin/bash

[[ -z $KEY ]] && exit 1
[[ -z $ETCDCTL_PEERS ]] && exit 1
[[ -z $FLEETCTL_ENDPOINT ]] && exit 1
[[ -z $FLEETCTL_TUNNEL ]] && exit 1

etcdctl ls /database/install || etcdctl mkdir /database/install
etcdctl get /database/installl/installing && exit 0
etcdctl get /database/install/complete && exit 0

etcdctl set --ttl=600 /database/install/installing 1

eval `ssh-agent`

fleetctl load systemd/* \
  && fleetctl start database-1-data.service \
  && fleetctl start database-2-data.service \
  && fleetctl start database-3-data.service \
  && sleep 10 \
  && fleetctl start database-1.service \
  && sleep 10 \
  && fleetctl start database-2.service \
  && fleetctl start database-3.service \
  && etcdctl set --ttl 0 /database/install/complete true \
  && etcdctl set --ttl 0 /database/install/installed_by $ETCDCTL_PEERS

etcdctl set --ttl=1 /database/install/installing 0
